### ISSUE TITLE
Make it possible to differentiate a SymmetricCipher from an AsymmetricCipher

### ISSUE THREAD

**Issue by koto** [google/end-to-end#106]
_From [evn@google.com](https://code.google.com/u/evn@google.com/) on June 13, 2014 21:14:36_

  
maybe add a method or property that needs to be @overriden by implementors.  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=69>

**Comment by koto** [comment]
I'm not sure what's that for. Reassigning.

**Comment by sirdarckcat** [comment]
the interface is the only thing we have for now, will reopen if this becomes an issue. it hasn't been one so far
