### ISSUE TITLE
e2e.cipher.RSA.decrypt does not re-add leading zero octets - bad for OAEP

### ISSUE THREAD

**Issue by koto** [google/end-to-end#108]
_From [scoo...@gmail.com](https://code.google.com/u/118176843894749104683/) on June 15, 2014 11:41:34_

  
**Steps to reproduce:**  
1\. Encode some data with the e2e.pkcs.eme.Oaep padding scheme. Note that the resulting encoded message begins with a zero octet (per [RFC3447](/p/end-to-end/source/detail?r=FC3447) 7.1.1 - step 2.i).  
2\. Call e2e.cipher.RSA.encrypt on the encoded data  
3\. Call e2e.cipher.RSA.decrypt on the output of step 2 ... note that the resulting array is one element smaller than what was sent in to encrypt()  
4\. Try to call e2e.pkcs.eme.Oaep.decodeForTestingOnly() - note that it considers the lack of a leading zero octet to be an error.  
  
**What happens?**  
  
When e2e.cipher.RSA.decrypt calls deblinded.toByteArray(), BigNum strips leading zeros. This causes decrypt() to return less data than encrypt() received.  
  
**What do you expect to happen instead?**  
  
e2e.cipher.RSA.decrypt() should always return an octet string of length k. That is, BigNum() strips them, but decrypt() is expected to prepend zero octets to keep the output length at k.  
  
References for this (in [RFC3447](/p/end-to-end/source/detail?r=FC3447)):  
  
1\. Section 4.1 step #2:  
where 0 <= x_i < 256 (note that one or more leading digits will be  
zero if x is less than 256^(xLen-1)).  
  
2\. Section 7.1.2 step #2.c, 7.2.2 step #2.c, and 8.1.2 step #2.c:  
  
Convert the message representative m to an encoded message EM  
of length k octets (see Section 4.1):  
  
EM = I2OSP (m, k).  
  
  
Notes  
\------------------  
1\. Yes, I'm referencing OAEP even though you don't have a time-constant decode method... let's pretend I have a safe decode method I'm using.  
  
2\. The attached example has private keys in it. The private keys are part of the JOSE-JWE test vectors and are safe to share.  
  
3\. This is fine for PKCS1, since it will never have leading zeros.  
  
4\. I can prepend my own leading zero when I know OAEP is in use... I am doing that now, but I'm hopeful that it is a temporary hack.  
  

**Attachment:** [rsa-oaep_test.html](http://code.google.com/p/end-to-end/issues/detail?id=71)

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=71>

**Comment by sirdarckcat** [comment]
if there's more requests for OAEP lets reopen this, otherwise closing this
