### ISSUE TITLE
Zimbra Web mail client's To: will include the signed message making the composed email invalid

### ISSUE THREAD

**Issue by koto** [google/end-to-end#121]
_From [allan.re...@gmail.com](https://code.google.com/u/112212012808666485463/) on June 20, 2014 07:04:25_

  
**Steps to reproduce:**  
1\. Login to your zimbra web mail (using google-chrome with end-to-end ext installed)  
2\. Compose new mail and write your recipient's email add  
3\. Type your subject and type some text in the body mail  
4\. Click the End-To-End icon at the right portion of the google-chrome window  
5\. Make sure to check the 'Sign this message' check box  
6\. Click 'Protect this message' button  
7\. Then click 'Insert into the page' button  
  
**What happens?**  
As expected, the mail(body) message got signed, but the whole signed message was appended to the To: textbox in after the recipient's email.  
  
  
**What do you expect to happen instead?**  
The To: TextBox is for the recipient's email addresses obviously.  
  
**== PLEASE DONT PUT ANY KEYS HERE ==**  
  
**If you are having trouble with a specific message or key, please follow**  
**these instructions:**  
  
**Debug instructions:**  
1\. Please build the extension and go to chrome-extension://<extension-  
id>/prompt.html and try to encrypt, decrypt or import a key from there.  
**2\. Note the error shown in red (if any)**  
3\. Open the JavaScript console (Tools -> JavaScript Console)  
**4\. Copy the output from the console here.**  
  
  
  
  
**Have you tested if this key/message works in other implementations? (PGP**  
**Desktop, GnuPG, etc..)**  
  
-It works on gmail.  
  
  
  
If you can, please copy the output of gpg --list-packets <filename>.  
  
-N/A  
  
**== DO NOT UPLOAD ANY KEYS PLEASE ==**  
  

**Attachment:** [test_encryp_e2e.png](http://code.google.com/p/end-to-end/issues/detail?id=84)

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=84>

**Comment by sirdarckcat** [comment]
if we get more requests for interop with zimbra lets reopen this
