### ISSUE TITLE
Stacking dialog boxes, background UI not disabled, background click does not close dialog box

### ISSUE THREAD

**Issue by koto** [google/end-to-end#137]
_From [rcc@google.com](https://code.google.com/u/rcc@google.com/) on July 03, 2014 01:07:59_

  
**Steps to reproduce:**  
1\. Click e2e icon  
2\. Click compose message  
3\. Click protect with passphrase  
4.1 Go to step 3 (without hitting enter passphrase or cancel)  
or  
4.2 Interact with a background UI element  
or  
4.3 Click somewhere in the background  
  
**What happens?**  
Many passphrase prompt dialogs stack on top of each other  
  
**What do you expect to happen instead?**  
  
1\. There should not be multiple dialog boxes open/stacked  
2\. The background elements should be disabled when a dialog box is open  
3\. The dialog box to be closed when I click on the background outside the dialog box  
  
  
**== PLEASE DONT PUT ANY KEYS HERE ==**  
  
**If you are having trouble with a specific message or key, please follow**  
**these instructions:**  
  
**Debug instructions:**  
1\. Please build the extension and go to chrome-extension://<extension-  
id>/prompt.html and try to encrypt, decrypt or import a key from there.  
**2\. Note the error shown in red (if any)**  
3\. Open the JavaScript console (Tools -> JavaScript Console)  
**4\. Copy the output from the console here.**  
  
  
  
  
  
  
**Have you tested if this key/message works in other implementations? (PGP**  
**Desktop, GnuPG, etc..)**  
  
  
  
  
  
If you can, please copy the output of gpg --list-packets <filename>.  
  
  
  
  
**== DO NOT UPLOAD ANY KEYS PLEASE ==**  
  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=100>

**Comment by sirdarckcat** [comment]
cleaning up old bugs, please reopen if you would still like to see this fixed
