### ISSUE TITLE
Improve performance in v8

### ISSUE THREAD

**Issue by koto** [google/end-to-end#157]
_From [koto@google.com](https://code.google.com/u/koto@google.com/) on July 23, 2014 19:39:18_

Make changes to the library that remove the bottlenecks when running e2e under v8. Ensure no timing leaks are introduces in the process.   
  
This will include:   
 * Move to typed arrays   
 * Using constant number of arguments when calling performance-critical functions (modExp_,modMul_)   
 * Removing out-of-bounds read array accesses. These poison the array and make it slow forever.   

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=120>

**Comment by sirdarckcat** [comment]
koto, let me know if you still planned to work on this, otherwise closing as we seem to have moved this to v8
