### ISSUE TITLE
Add support to search key by fingerprint to the key server

### ISSUE THREAD

**Issue by koto** [google/end-to-end#172]
_From [evn@google.com](https://code.google.com/u/evn@google.com/) on August 23, 2014 01:06:11_

  
We need it to be able to bruteforce keys based on fingerprint and to be able to fetch status and so on.  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=135>

**Comment by zachriggle** [comment]
Even better than searching by key fingerprint would be to search by email and even cross-reference the key ID with Keybase.io.  Then those can be cross-referenced with the provided proofs of ownership.

https://keybase.io/docs/api/1.0/call/key/fetch

**Comment by sirdarckcat** [comment]
this is deprecated, the new key server will behave a bit differently
