### ISSUE TITLE
Automatically ask user for backup code if a key already exists in key server

### ISSUE THREAD

**Issue by koto** [google/end-to-end#173]
_From [evn@google.com](https://code.google.com/u/evn@google.com/) on August 23, 2014 01:09:51_

  
Otherwise the user is very likely to accidentally overwrite his old key.  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=136>

**Comment by sirdarckcat** [comment]
lets keep track of this in https://github.com/google/end-to-end/issues/353
