### ISSUE TITLE
Unable to decrypt emails with bzip2 compression (seemingly)

### ISSUE THREAD

**Issue by koto** [google/end-to-end#182]
_From [mich...@sykosoft.com](https://code.google.com/u/115527667706391427261/) on September 04, 2014 01:59:53_

  
**Steps to reproduce:**  
1\. Send message from client supporting bzip2 (thunderbird?)  
2\. Receive and attempt to decrypt  
3\. Received message  
  
**What happens?**  
  
"Required algorithm not available."  
  
**What do you expect to happen instead?**  
  
Decryption of message.  
  
**== PLEASE DONT PUT ANY KEYS HERE ==**  
  
**If you are having trouble with a specific message or key, please follow**  
**these instructions:**  
  
**Debug instructions:**  
1\. Please build the extension and go to chrome-extension://<extension-  
id>/prompt.html and try to encrypt, decrypt or import a key from there.  
**2\. Note the error shown in red (if any)**  
3\. Open the JavaScript console (Tools -> JavaScript Console)  
**4\. Copy the output from the console here.**  
  
  
  
  
  
  
**Have you tested if this key/message works in other implementations? (PGP**  
**Desktop, GnuPG, etc..)**  
  
  
  
  
  
If you can, please copy the output of gpg --list-packets <filename>.  
  
  
  
  
**== DO NOT UPLOAD ANY KEYS PLEASE ==**  
  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=145>

**Comment by sykosoft** [comment]
Any updates on this? bzip is a blocking feature for (at least) my daily use, given that it is well supported by other implementations.

**Comment by dlg-yahoo** [comment]
PNaCl?

**Comment by adhintz** [comment]
I'll take a look at this.
@sykosoft , I believe compatible licenses would be Apache, MIT, or BSD. All of the existing bzip2 implementations in JavaScript that I've been able to find are LGPL and have a confusing copyright history. They typically are adapted from antimatter15's BSD-licensed code, which is based on landley's LGPL code, which is based on Seward's BSD-licensed code.

Unless someone knows about a bzip2 implementation in JavaScript with a known copyright lineage, I'll probably implement decompression myself.

**Comment by sykosoft** [comment]
@adhintz Unfortunately, no. I only know of GPL (and derivatives) licensed implementations. That's unfortunate.

**Comment by sykosoft** [comment]
I got all excited, but it looks like it's not yet complete.....

**Comment by adhintz** [comment]
@sykosoft Yeah, not complete at all. Just a basic bit reader and some of the template code for the compression library.

**Comment by sykosoft** [comment]
@koto Any updates on this? It's still a blocking issue for receipt of messages simply sent through other products.

**Comment by koto** [comment]
No, there's no active work at the compression side of things now. As for other products sending you bzip, this should be solved by specifying preferred compression algos in your public key: https://tools.ietf.org/html/rfc4880#section-5.2.3.9. FWIW only ZIP is a must algorithm (https://tools.ietf.org/html/rfc4880#section-9.3), so other OpenPGP implementations should not compress using bzip without that support being advertised by the key owner.

Is some implementation behaving differently? Which one?

**Comment by adhintz** [comment]
I've made some progress on this. A draft of my code can successfully decode a simple bz2 block. I still need to do more testing and work on it.

I only expect that I'll implement decompression -- I don't have plans to implement compression. It seems that e2e.compression.Algorithm expects algorithms to have both compress and decompress. Should I refactor that or special-case bzip2?
