### ISSUE TITLE
Prompt to set keyring passphrase when importing passphrase-protected secret keys to an unencrypted keyring

### ISSUE THREAD

**Issue by koto** [google/end-to-end#184]
_From [adhintz@google.com](https://code.google.com/u/adhintz@google.com/) on September 04, 2014 19:15:28_

  
Because we use one keyring-wide passphrase instead of more traditional per-key passphrases, some users are unintentionally importing secret keys to an unencrypted keyring. We should inform the user when this is happening and give them the option to set the passphrase for their keyring.   
  
Proposed flow:   
When the user attempts to import a passphrase-protected secret key, if the local keyring is unencrypted, prompt the user before asking for the imported key's passphrase. In the prompt, inform the user and give them the option to 1) leave their keyring unencrypted or 2) set the keyring passphrase to the passphrase for the secret key that's about to be imported.  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=147>

**Comment by sirdarckcat** [comment]
closing up old bugs, please reopen if you would still like to see it fixed
