### ISSUE TITLE
Large PGP message in Gmail causes errors

### ISSUE THREAD

**Issue by koto** [google/end-to-end#185]
_From [billyleo...@google.com](https://code.google.com/u/114122973773271828744/) on September 11, 2014 18:29:37_

  
**Steps to reproduce:**  
1\. Send large pgp encrypted email that Gmail does not fully display without clicking 'View Entire Message'  
2\. Try to decrypt with end-to-end  
  
**What happens?**  
end-to-end fails with 'invalid ASCII armor format'  
when closing and reopening the message, end-to-end immediately tries to decrypt causing problems with clicking the 'View Entire Message' link as it's not rendered as plain text in the end-to-end window  
  
**What do you expect to happen instead?**  
Allow me to click 'View Entire Message' so I can view/decrypt the whole message.  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=148>

**Comment by sirdarckcat** [comment]
without looking glass this shouldn't be an issue anymore, I think
