### ISSUE TITLE
Feature Request: Key QR Code export

### ISSUE THREAD

**Issue by koto** [google/end-to-end#195]
_From [rum...@google.com](https://code.google.com/u/110046148200173983257/) on November 13, 2014 20:05:20_

  
It'd be awesome if the public and private keys could be rendered as QR Codes, so that these can be easily imported into mobile phones, e.g. OpenKeychain.   
  
For the public key, it'd probably be easiest to use the Google charts API to render the QR code image.   
For the private key sending it somewhere else may not be a good idea, so rendering could use a library like qrcodejs.  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=158>

**Comment by koto** [comment]
All various private/public key exports are part of a KeyRing redesign that now takes place.

**Comment by sirdarckcat** [comment]
if someone wants to take this over, please reopen the issue for further discussion.
