### ISSUE TITLE
Support for Fq(M521) mostly absent

### ISSUE THREAD

**Issue by dlg-yahoo** [google/end-to-end#202]
The crypto library doesn't support fast operations over the prime field Fq(2^521-1).

Things needed:
  1. Test cases
  2. Mersenne reduction
  3. "Granger-Scott" multiplication
  4. Possibly: floating-point Mersenne multiplication via DFT

I've done some work on (1) and (2); less on (3).

**Comment by koto** [comment]
Any update on this?

**Comment by sirdarckcat** [comment]
asked thai/frank/quan if they are interested

**Comment by sirdarckcat** [comment]
as we dont use prime 521, it didn't seem worth optimizing. please reopen if you feel otherwise
