### ISSUE TITLE
Clicking the extension icon does not detect clearsigned messages.

### ISSUE THREAD

**Issue by beow** [google/end-to-end#206]
I'm a "layman" with respect to pgp and pki etc. but interested in the subject and wan't to help out from my perspective (if this is the right forum and you're interested). Have installed the extension on my mac from the build instructions that were good (once I understood that "ant" was given by the macports "apache-ant" package). 

1.a Then imported my secring from my .gnupg folder. (It was not clear which to import secring or pubring, but I assumed secring at least would be needed). 

1.b Tested to send an encrypted mail to myself. Needed a pass-phrase to encrypt the message (and subsequently to de-crypt it). What was happening here? e2e did not at this stage have my public key. Some kind of symmetric encoding using my secret key???

2. Anyway, I then imported my pubring and then I could send encrypted messages to myself by using the address drop-down and could then decrypt it easily from the e2e extension. So this seems all fine.

3. Last I tried to send myself a signed only message (by not choosing recipient from the extension as described in the FAQ). When I got the message there was no way to verify the signature. When clicking the extension icon I was offered to encrypt the received message. Am I missing something?

**Comment by koto** [comment]
OK, I found the steps to reproduce your issue:

1. Go to Gmail
2. Clearsign a message (Create a message to yourself, having 'sing this message' checked, but not selecting any recipients).
3. Click 'Insert this message into compose window'
4. Having the compose window focused, click the extension icon. 

What happens?
Compose window is displayed, with the clearsigned message

What should happen?
Read message window should appear.

As a workaround, you can still verify the message manually by clicking on the ![down arrow](https://raw.githubusercontent.com/google/end-to-end/master/src/javascript/crypto/e2e/extension/images/down_arrow.png)  button in the extension dialog, choosing 'read a protected message' and clicking 'read'.
