### ISSUE TITLE
Remove OTRv1.

### ISSUE THREAD

**Issue by DrWhax** [google/end-to-end#207]
I want to make you aware that we're(otr team) working towards removing OTRv1 from libotr rather sooner than later. I think that there is only one implementation that supports OTRv1 and that is libotr. 

We finally got a good test-suite in that is going to be merged soon to _master_ and makes it easier to remove this code and purge it forever.

There is no reason, at this point in time, to leave OTRv1 in code. We would be very happy at OTR if this could be removed from the code.

https://bugs.otr.im/issues/40

**Comment by dlg-yahoo** [comment]
+1

**Comment by koto** [comment]
We only use OTRv3 (see e.g. https://github.com/google/end-to-end/blob/master/src/javascript/crypto/e2e/otr/message/query.js#L142). The only v1 code is the one detecting the version in message parsing.
