### ISSUE TITLE
OSX build issue: Ant is required to build End-To-End

### ISSUE THREAD

**Issue by lunokhod** [google/end-to-end#210]
Builing on OSX gives the following error:

    Ant is required to build End-To-End

This is easily fixed by installed apache-ant via port

**Comment by asteppa** [comment]
If I'm running the build in Cygwin on Windows, how can I best install Ant?

**Comment by koto** [comment]
Yes, Ant is required and it's documented at https://github.com/google/end-to-end/wiki/Build-instructions. We don't provide instructions on how to install Ant on various platforms (on OSX alone there's at least Homebrew and Macports way).
