### ISSUE TITLE
Flow of Program Code

### ISSUE THREAD

**Issue by asteppa** [google/end-to-end#211]
I'm trying to understand the exact order of operations of the extension code. Is there a script of some sort that organizes events?

**Comment by koto** [comment]
Chrome extensions have multiple parts in them that we use in E2E, so it's best to first familiarize yourself with Chrome Extensions development and what are the various moving parts of them. 

The extension UI is constructed of `ui.Prompt` element, that gets rendered when the user presses the extension `browser_action` button. There are different `Panel`s in the `Prompt` that display various UI panels, like compose, read message and import key panel. All event handling related to user actions (clicks) happens in the `Prompt` or one of its `Panel`s. Prompt only accesses crypto code through the `Launcher`.

The `Launcher` is created in a background script (so it runs persistently). It is mainly responsible for accessing the `opengpg.ContextImpl` instance, that exposes all crypto & key related operations. 

To get the data from/into the web applications a `Helper` object is injected into a content script of the current tab. `Helper` handles the communication between the extension code running in a background page (or directly in a prompt page) and its internal object - `WebsiteApi`. That one implements the [Website API](https://github.com/google/end-to-end/wiki/Website-API) protocol to allow arbitrary websites speaking to E2E. For some applications (currently, Gmail), `WebsiteAPI` injects a stub script to enrich the website with `Website API` support. 

So usually it goes like this:
1. User click the button
2. Prompt gets created
3. Prompt calls getSelectedContent()
4. Through the Launcher, a helper content script (helper_binary.js) is injected into current tab (say, with Gmail)
5. The script contains a `Helper` object that forwards the call to `WebsiteApi`
6. WebsiteApi detects the origin of the page and injects a `gmonkeystub.js` into Gmail.
7. `gmonkeystub.js` uses Gmail APIs to get the current content and passes it back to WebsiteApi.
8. It goes all the way up back to prompt.
9. User composes the message, and encrypts it. All crypto & keyring operations are being done through the `Launcher`, through `ContextImpl`
10. When it's ready, he presses the button to sent the encrypted message back into Gmail. The message goes the usual way to the `Helper`, `Website API`, and finally reaches Gmail.

As this was only a question and not an issue, I'll close it.
