### ISSUE TITLE
ERROR - Duplicate input: lib\closure-library\closure\goog\deps.js

### ISSUE THREAD

**Issue by asteppa** [google/end-to-end#212]
I keep encountering the following error when trying to build the program

.ERROR - Duplicate input: lib\closure-library\closure\goog\deps.js

**Comment by koto** [comment]
Could you try removing the contents of the `lib/` subdirectory and doing `./do.sh install_deps` again? I just checked, and I can  [build the project](https://github.com/google/end-to-end/wiki/Build-instructions) from scratch without any problems. The whole process is:
```
git clone https://github.com/google/end-to-end
cd end-to-end/
./do.sh install_deps
./do.sh build_extension
```

If that doesn't help, what's your platform? Can you paste the output of doing `./do.sh install_deps` on a fresh copy?

**Comment by asteppa** [comment]
I'm running the program on Windows with Cygwin Terminal. This is the output of ./do.sh install_deps on a clean copy: 

$ ./do.sh install_deps
Installing build dependencies...
Cloning into 'closure-library'...
remote: Counting objects: 2588, done.
remote: Compressing objects: 100% (1989/1989), done.
remote: Total 2588 (delta 826), reused 1194 (delta 574)
Receiving objects: 100% (2588/2588), 4.53 MiB | 4.04 MiB/s, done.
Resolving deltas: 100% (826/826), done.
Checking connectivity... done.
Checking out files: 100% (2437/2437), done.
Cloning into 'zlib.js'...
remote: Counting objects: 112, done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 112 (delta 17), reused 55 (delta 12)
Receiving objects: 100% (112/112), 5.67 MiB | 6.66 MiB/s, done.
Resolving deltas: 100% (17/17), done.
Checking connectivity... done.
Cloning into 'closure-compiler'...
remote: Counting objects: 1089, done.
remote: Compressing objects: 100% (976/976), done.
remote: Total 1089 (delta 250), reused 294 (delta 96)
Receiving objects: 100% (1089/1089), 7.18 MiB | 6.62 MiB/s, done.
Resolving deltas: 100% (250/250), done.
Checking connectivity... done.
Checking out files: 100% (1027/1027), done.
Buildfile: C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\build.xml

relversion:

compile:
    [mkdir] Created dir: C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\build\classes
    [javac] Compiling 12 source files to C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\build\classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] 1 warning
    [javac] Compiling 553 source files to C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\build\classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\src\com\google\javascript\jscomp\DefaultPassConfig.java:279: warning: [deprecation] checkRequires in CompilerOptions has been deprecated
    [javac]     if (options.checkRequires.isOn()
    [javac]                ^
    [javac] C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\src\com\google\javascript\jscomp\WarningLevel.java:58: warning: [deprecation] checkRequires in CompilerOptions has been deprecated
    [javac]     options.checkRequires = CheckLevel.OFF;
    [javac]            ^
    [javac] 3 warnings
    [mkdir] Created dir: C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\build\classes\rhino_ast\java\com\google\javascript\rhino
     [copy] Copying 1 file to C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\build\classes\rhino_ast\java\com\google\javascript\rhino
     [copy] Copying 1 file to C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\build\classes\com\google\javascript\jscomp\parsing
[propertyfile] Updating property file: C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\build\classes\com\google\javascript\jscomp\parsing\ParserConfig.properties
    [mkdir] Created dir: C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\build\classes\com\google\javascript\jscomp\js
     [copy] Copying 3 files to C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\build\classes\com\google\javascript\jscomp\js

jar:
      [zip] Building zip: C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\build\externs.zip
      [jar] Building jar: C:\cygwin64\home\Aaron\new\end-to-end\lib\closure-compiler\build\compiler.jar

BUILD SUCCESSFUL
Total time: 36 seconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.5M  100 12.5M    0     0  6090k      0  0:00:02  0:00:02 --:--:-- 6229k
Archive:  closure-templates-for-javascript-latest.zip
  inflating: closure-templates-compiler/COPYING
  inflating: closure-templates-compiler/README
  inflating: closure-templates-compiler/SoyToJsSrcCompiler.jar
  inflating: closure-templates-compiler/soyutils.js
  inflating: closure-templates-compiler/soyutils_usegoog.js
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2188k  100 2188k    0     0  3344k      0 --:--:-- --:--:-- --:--:-- 3678k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  196k  100  196k    0     0   655k      0 --:--:-- --:--:-- --:--:--  772k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 80438  100 80438    0     0   446k      0 --:--:-- --:--:-- --:--:--  464k
Done.

**Comment by koto** [comment]
Thanks. We don't really support building with Cygwin, there's quite a few things that might go wrong with such a set up, but you could try e.g. changing the symlinks settings http://stackoverflow.com/questions/3648819/how-to-make-symbolic-link-with-cygwin-in-windows-7 .
