### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by asteppa** [google/end-to-end#213]
When attempting to build the program in Ubuntu I keep running into the following errors:

All dependencies met.
All dependencies met.
Compiling Soy templates...
Done.
Using previous template build - ./do.sh clean if you with to rebuild the templates.
Building End-To-End extension to build/extension
Compiling JS files...
.lib/closure-library/closure/goog/functions/functions.js:130: ERROR - Bad type annotation. type not recognized due to syntax error
 * @return {function(...[?]):T} A new function.
                        ^

lib/closure-library/closure/goog/functions/functions.js:159: ERROR - Bad type annotation. type not recognized due to syntax error
 * @param {function(...[?]):T} fn The final function.
                       ^

lib/closure-library/closure/goog/functions/functions.js:161: ERROR - Bad type annotation. type not recognized due to syntax error
 * @return {function(...[?]):T} The composition of all inputs.
                        ^

lib/closure-library/closure/goog/functions/functions.js:207: ERROR - Bad type annotation. type not recognized due to syntax error
 * @return {function(...[?]):boolean} A function that ANDs its component
                        ^

lib/closure-library/closure/goog/functions/functions.js:230: ERROR - Bad type annotation. type not recognized due to syntax error
 * @return {function(...[?]):boolean} A function that ORs its component
                        ^

lib/closure-library/closure/goog/functions/functions.js:251: ERROR - Bad type annotation. type not recognized due to syntax error
 * @return {function(...[?]):boolean} A function that delegates to f and returns
                        ^

lib/closure-library/closure/goog/iter/iter.js:893: ERROR - Bad type annotation. type not recognized due to syntax error
 * @param {function(...[VALUE]): KEY=} opt_keyFunc  Optional function for
                       ^

lib/closure-library/closure/goog/iter/iter.js:913: ERROR - Bad type annotation. type not recognized due to syntax error
   * @type {function(...[VALUE]): KEY}
                        ^

lib/closure-library/closure/goog/iter/iter.js:983: ERROR - Bad type annotation. type not recognized due to syntax error
 * @param {function(...[VALUE]): KEY=} opt_keyFunc  Optional function for
                       ^

lib/closure-library/closure/goog/iter/iter.js:1005: ERROR - Bad type annotation. type not recognized due to syntax error
 * @param {function(this:THIS,...[*]):RESULT} f The function to call for every
                                 ^

lib/closure-library/closure/goog/promise/thenable.js:79: ERROR - Bad type annotation. type not recognized due to syntax error
 * @param {function(new:goog.Thenable,...[?])} ctor The class constructor. The
                                         ^

src/javascript/crypto/e2e/compression/factory.js:39: ERROR - Bad type annotation. type not recognized due to syntax error
 * @param {function(new:e2e.compression.Compression, ...[*])}
                                                        ^

src/javascript/crypto/e2e/hash/factory.js:39: ERROR - Bad type annotation. type not recognized due to syntax error
 * @param {function(new:e2e.hash.Hash, ...[*])} hash The constructor of
                                          ^

13 error(s), 0 warning(s)

How can I fix these issues?

**Comment by koto** [comment]
It seems you're hitting this [bug in Closure Library](https://github.com/google/closure-library/issues/395). A workaround is to compile with the older version of Closure Compiler (a recent commit introduced this error):

```
# Switch to the older version of the compiler
cd lib
rm -rf closure-compiler/
git clone https://github.com/google/closure-compiler
git checkout 6e278129346963e3baafb92a68f46b5802915a10
# Compile the compiler
ant jar
cd ../..
./do.sh build_extension
```

**Comment by leppert** [comment]
@koto This still throws an error for me using the recommended closure-compiler version:

```
.lib/closure-library/closure/goog/crypt/sha2.js:201: ERROR - Bad type annotation. missing closing >
 *  @param {Array.<Uint32Array[80]>} precomputed_schedule An SHA2-32b schedule
                              ^

1 error(s), 0 warning(s)
```

**Comment by michaelfoley1** [comment]
I have the same issue.

```
Compiling JS files...
.lib/closure-library/closure/goog/crypt/sha2.js:201: ERROR - Bad type annotation. missing closing >
 *  @param {Array.<Uint32Array[80]>} precomputed_schedule An SHA2-32b schedule
                              ^

1 error(s), 0 warning(s)
```

**Comment by koto** [comment]
It's a Closure library issue - https://github.com/google/closure-library/issues/402. It's gone once "[80]" is removed from the `sha2.js` source file , but I don't know if library authors want to apply that fix.
