### ISSUE TITLE
status? 

### ISSUE THREAD

**Issue by Maxhodges** [google/end-to-end#220]
No contributions for 3-4 months. Does that mean it's going to be released to beta soon?
The world needs this.
GCHQ captured emails of journalists from top international media
• Snowden files reveal emails of BBC, NY Times and more
• Agency includes investigative journalists on ‘threat’ list

http://www.theguardian.com/uk-news/2015/jan/19/gchq-intercepted-emails-journalists-ny-times-bbc-guardian-le-monde-reuters-nbc-washington-post

**Comment by koto** [comment]
We are actively working on End-To-End, last push to external repository was done in December, and there are some new commits incoming soon.

**Comment by dlg-yahoo** [comment]
Same for Yahoo.It is likely we will also release a (temporary) fork for some Ymail-specific integration that currently is hard to merge into mainline. (Easier to use, but slightly weaker safety properties in the current security model.)

**Comment by adhintz** [comment]
Closing this. Thanks for the interest and please feel free to reopen if you have more questions.

**Comment by hsynkrtl** [comment]
http://m.heise.de/newsticker/meldung/Web-de-und-GMX-fuehren-PGP-Verschluesselung-fuer-Mail-ein-2786133.html

Can't wait to use e2e. When you going to release it to the public.
