### ISSUE TITLE
Hands on problems (cannot decrypt message)

### ISSUE THREAD

**Issue by shavvn** [google/end-to-end#222]
Hi, I'm new to this project and met some problems when I try to get my hands on it.

Here is what I did:

1. build the extension

2. load it  into chromes of 2 computers A and B, and launch them

3. For computer A, sign up a account, A@gmail.com; for computer B, sign up B@gmail.com

4. export public keys of A and B and import to each other so that they have pub-keys of the other

5. compose a message on computer from A to B (now it has B in the drop down list), click the "protect the message" and get an encrypted message like:

-----BEGIN PGP MESSAGE-----
FOO
-----END PGP MESSAGE-----

6. paste it into B's "Read a protected message" and the "read" button just wouldn't work, i.e. no response at all. 

end-to-end version: 0.4, chrome version: 40.0.2214.91

I'm sure it's my problem since you all worked it out. It would be great if you could point out where I went wrong.

Thanks

**Comment by koto** [comment]
How did you manage to get end-to-end version 0.4? Currently we're at
```
Version: End-To-End v0.3.1342
```
Instead of copying/pasting, did you try to send the message through Gmail? Is there any error message displayed?

**Comment by shavvn** [comment]
Hi koto,

Thank you for your reply! When I tried to build the extension  I used the */src/javascript/crypto/e2e/extension/app_manifiest.jason* instead of *extension_manifest.json* cause I thought it was a newer version.. I would rebuild the extension to v0.3 and come back with my results.

Thanks

**Comment by shavvn** [comment]
Indeed I should use the v0.3 manifest file. Now it works well. But I guess it would be better if you could specify which file should be used to build the extension (by default the file name is *manifest.jason*" ,which is not in the source directory.)

You may close this thread now, thank you.
