### ISSUE TITLE
Multiple keyrings

### ISSUE THREAD

**Issue by orrion** [google/end-to-end#223]
Hi guys, I was wondering if it is possible to import two different keyrings with different pass phrases. For example if I imported private key into keyring with one pass phrase and after that I want to import another private key with another pass phrase, is this possible? For now if I try to set another pass phrase for keyring it says that "Error: HMAC does not match! LocalStorage modified?".

**Comment by koto** [comment]
We only support a single passphrase, if you need to have multiple secret keyrings (with differing passphrases), you could use E2E in different browser profiles.

**Comment by orrion** [comment]
@koto OK, thanks a lot for your response!

**Comment by orrion** [comment]
@koto As I saw there is a local storage key where the keyring is stored... this key is "UserKeyRing". Maybe if I add something (for example current user email) to this key then I would have different keyring, right?

**Comment by koto** [comment]
Well, you can do anything really, it's open source, but we won't support multiple keyrings. You might have  to reengineer the code to make ContextImpl compatible with multiple keyrings or have some sort of keyring switching mechanism.

**Comment by orrion** [comment]
Thanks @koto for your response. It would be great to have multiple keyring support, cos computer may be used by multiple users (for example family or roommates) and they also can use one browser account (or no account at all..), so this means that all of them will have access to each others private keys....

**Comment by koto** [comment]
Shared browser profile is definitely not the recommended approach, and the one we do not design for. With a shared profile you share the cookies (so a login state), extensions, apps, passwords, history and a bunch of other things. Browser profiles provide the least amount of separation needed. Shared computers are not such a good idea too to protect your private keys (other user can just install a keylogger).

**Comment by orrion** [comment]
Well, here in Ukraine there are a lot of users that do not care about browser profiles (university labs, students in hostels, etc..) :) OK, thank you, security is everything! :)
