### ISSUE TITLE
attempting searchable symmetric encryption

### ISSUE THREAD

**Issue by asteppa** [google/end-to-end#227]
Hi,

We are trying to build onto the End-to-End code, a searchable symmetric encryption functionality. This requires storing encrypted information on a third party cloud server. We are attempting to use parse.com, but is there a google solution for this that already exists that you would recommend?

**Comment by sirdarckcat** [comment]
cleaning up old bugs.

not sure if this is still relevant, but no.. we don't know of a good place to store the encrypted information. we investigated a bit on searchable encryption, but found it heavily weakened our security model, so we haven't worked on it anymore since then.
