### ISSUE TITLE
App build problems

### ISSUE THREAD

**Issue by dlg-yahoo** [google/end-to-end#230]
I'm getting this error when I try to build:
```
....src/javascript/crypto/e2e/extension/ui/prompt/prompt.js:204: ERROR - Property getSelectedContent never defined on this.helperProxy_
      this.helperProxy_.getSelectedContent(
```

In addition, the current `do.sh` is still incorrect.

Is this a correct merge? (I suspect that you're testing without fulling cleaning out detritus from an internal build....)

**Comment by koto** [comment]
David, have you tried this with https://github.com/google/end-to-end/pull/229 applied? We have this a two-pairs-of-eyes rule, so I can't merge this PR myself.

**Comment by dlg-yahoo** [comment]
I'll take a look.

**Comment by lunokhod** [comment]
Same problem on OSX. No, I haven't tried the above patch. I did ```./do sh clean``` so I don't know why I am getting that error.

````
 ./do.sh build_extension
All dependencies met.
All dependencies met.
Compiling Soy templates...
Done.
Using previous template build - ./do.sh clean if you with to rebuild the templates.
Building End-To-End extension to build/extension
Compiling JS files...
....src/javascript/crypto/e2e/extension/ui/prompt/prompt.js:204: ERROR - Property getSelectedContent never defined on this.helperProxy_
      this.helperProxy_.getSelectedContent(
````

**Comment by koto** [comment]
OK, I can repro that. Investigating...

**Comment by koto** [comment]
Found it - a quick patch: 

```
diff --git a/src/javascript/crypto/e2e/extension/ui/prompt/prompt.js b/src/javascript/crypto/e2e/extension/ui/prompt/prompt.js
index 174e1bf..f450682 100644
--- a/src/javascript/crypto/e2e/extension/ui/prompt/prompt.js
+++ b/src/javascript/crypto/e2e/extension/ui/prompt/prompt.js
@@ -194,7 +194,7 @@ ui.Prompt.prototype.enterDocument = function() {
         this.getElementByClass(constants.CssClass.POPOUT_BUTTON),
         constants.CssClass.HIDDEN);
   }
-  utils.action.getLauncher(function(launcher) {
+  utils.action.getLauncher(/** @this {ui.Prompt} */ (function(launcher) {
     this.pgpLauncher_ = launcher || this.pgpLauncher_;
     if (goog.isDefAndNotNull(this.injectedContent_)) {
       this.processSelectedContent_(this.injectedContent_);
@@ -207,7 +207,7 @@ ui.Prompt.prototype.enterDocument = function() {
               constants.Actions.USER_SPECIFIED)
       );
     }
-  }, this.displayFailure_, this);
+  }), this.displayFailure_, this);
 };
```

**Comment by mattrude** [comment]
The above patch resolved the problem for me, when building from current (146cfb57be).

**Comment by sitSearcher** [comment]
Sorry, but i´ve got the same problem.
I´m not as familiar with patching,..... can somebody tell me, how I can use/integrate the patch to get it work?

that would be really nice!

thanks!

**Comment by mattrude** [comment]
@sitSearcher, to apply a patch; copy the patch into a file, then while in the end-to-end root directory run `patch -p1 < the-name-of-the-file.txt`

**Comment by koto** [comment]
The current HEAD should build correctly, both #229 and the patch from https://github.com/google/end-to-end/issues/230#issuecomment-74106715 are now merged.

**Comment by sitSearcher** [comment]
@mattrude thanks for the descryption for further patches
@koto thanks for the fix. But the file "lib/closure-stylesheets-20111230.jar" in e2e_assert_dependencies() does not exist anymore. I found an other one in "/lib/closure-stylesheets/build/closure-stylesheets.jar". Is this the needed file?!

thanks a lot.

**Comment by DominicBoettger** [comment]
When compiling the extension i get this error:
..src/javascript/crypto/e2e/extension/helper/websiteapi.js:292: ERROR - actual parameter 1 of onPortReadyCallback does not match formal parameter
found   : (boolean|null)
required: boolean
      onPortReadyCallback(this.apiAvailable_);

**Comment by koto** [comment]
Thanks, I can reproduce this.
