### ISSUE TITLE
git submodules

### ISSUE THREAD

**Issue by dominichamon** [google/end-to-end#232]
the current dependency installation script uses explicit git clone. A simpler solution might be to use git submodules. This also allows the version of the dependency to be pinned to a specific SHA and protect against non-backwards compatible updates to the dependent libraries.

**Comment by dlg-yahoo** [comment]
Agree. Submit a PR.At Feb 13, 2015, 11:07:26 AM, Dominic Hamon wrote:the current dependency installation script uses explicit git clone. A simpler solution might be to use git submodules. This also allows the version of the dependency to be pinned to a specific SHA and protect against non-backwards compatible updates to the dependent libraries.

**Comment by koto** [comment]
Fixed in dd2869c9f6c1f2a2119066ddf6a9b03681e1166e.
