### ISSUE TITLE
Make it clear when the message is only encrypted to sender's key

### ISSUE THREAD

**Issue by Fastidious** [google/end-to-end#236]
It seems the current code (just clone today's) can encrypt fine, but when sending an email to a recipient for which we do not have a key, it will not just sign it, it will encrypt it (with my key, I assume) as well. That is worthless for the recipient. 

Is it not possible to simply sign--without encrypting--an email?

**Comment by koto** [comment]
Yes, I can reproduce it, thanks! As a workaround, in order to clearsign a message only, don't enter any recipient (or passphrase) into recipients list.

**Comment by Fastidious** [comment]
I saw the workaround--afterwards--on the FAQ. As long as it is on someone's to-do it will be all right. Closing this.

**Comment by daveloyall** [comment]
I recommend reopening this as a UX bug.  (Also, thanks for the workaround!)

**Comment by daveloyall** [comment]
And "make it clear how to sign a message (only, not encrypt)".  For example, if you want to post to a mailing list.

**Comment by sirdarckcat** [comment]
cleaning up old bugs, please reopen if you would still like to see this fixed
