### ISSUE TITLE
download-libs.sh `[[` test breaks some "sh" shells

### ISSUE THREAD

**Issue by rcchan** [google/end-to-end#237]
`[[` is not supported in all `sh` shells and is an extension of the POSIX standard.

When running `do.sh install_deps` this causes an error on my Debian 7 machine.

```
./download-libs.sh: 30: ./download-libs.sh: cannot open 1.7: No such file
./download-libs.sh: 30: ./download-libs.sh: [[: not found
```

The relevant code is reproduced below:

```shell
jversion=$(java -version 2>&1 | grep version | awk -F '"' '{print $2}')
if [[ $jversion < "1.7" ]]; then
  echo "Java 1.7 or higher is required to build End-To-End."
  exit 1
fi
```

Changing the shell to `bash` solved the problem for me although may not be the solution we're looking for if bash is not a dependency.  There are also other workarounds by using `sed` or `bc` to compare the version numbers since `[` doesn't seem to handle them natively.

**Comment by koto** [comment]
Thanks for spotting this. We'll move to `bash` in `download-libs.sh`.
