### ISSUE TITLE
ERROR in websiteapi.js

### ISSUE THREAD

**Issue by cb15** [google/end-to-end#239]
Hi there,

I have the following ERROR when trying to compile the extension:

./do.sh build_extension
All dependencies met.
Using previous template build - ./do.sh clean if you with to rebuild the templates.
Building End-To-End extension to build/extension
Compiling JS files...
Compiling JS files...
..src/javascript/crypto/e2e/extension/helper/websiteapi.js:292: ERROR - actual parameter 1 of onPortReadyCallback does not match formal parameter
found   : (boolean|null)
required: boolean
      onPortReadyCallback(this.apiAvailable_);
                          ^

1 error(s), 0 warning(s), 98,5% typed

CB

**Comment by koto** [comment]
Thanks, we're already in the process of pushing the fix.
