### ISSUE TITLE
Verification of signatures on PGP/Mime messages

### ISSUE THREAD

**Issue by lunokhod** [google/end-to-end#241]
At the present time, it appears that end-to-end is incapable of verifying the signature of a GPG signed message. This would obviously be a good feature to have....

**Comment by koto** [comment]
Do you have more information about the failing verification? Signature verification is supported, and we do test for this: https://github.com/google/end-to-end/blob/master/src/javascript/crypto/e2e/openpgp/compatibility_test.html#L1266

**Comment by lunokhod** [comment]
Actually, I think that what I found is that end-to-end can not verify PGP/Mime signatures. (If I understand correctly, end-to-end only validates PGP/Inline). The problem is that GPGMail on OSX generates PGP/Mime signatures.

After a long discussion with the GPG Mail folks, here is their response to this problem

> GPGMail defaults to the only standard there is for sending OpenPGP Mails, which is PGP/MIME. The format you are referring to, is called PGP/Inline and is an undocumented non-standard format, which leads to several problems, which is why we default to PGP/MIME.

So, my question is: Is there a way to validate a signed message sent from GPGMail? Here is an example of such a message.

```
Delivered-To: xxx.xxx@xxx.com
Received: by 10.25.32.149 with SMTP id g143csp1234154lfg;
        Wed, 18 Mar 2015 06:23:01 -0700 (PDT)
X-Received: by 10.112.89.71 with SMTP id bm7mr36828015lbb.20.1426684980998;
        Wed, 18 Mar 2015 06:23:00 -0700 (PDT)
Return-Path: <lunokhod@i2pmail.org>
Received: from mail01.sigterm.no ([193.150.121.27])
        by mx.google.com with ESMTPS id dy5si12891564lac.130.2015.03.18.06.23.00
        for <xxx.xxx@xxx.com>
        (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Wed, 18 Mar 2015 06:23:00 -0700 (PDT)
Received-SPF: pass (google.com: domain of lunokhod@i2pmail.org designates 193.150.121.27 as permitted sender) client-ip=193.150.121.27;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of lunokhod@i2pmail.org designates 193.150.121.27 as permitted sender) smtp.mail=lunokhod@i2pmail.org
Received: from smtp.postman.i2p (unknown [193.150.121.26])
	by postman.meeh.i2p (Postfix) with ESMTP id 042C62E3411
	for <xxx.xxx@xxx.com>; Wed, 18 Mar 2015 14:22:59 +0100 (CET)
X-Virus-Scanned: clamav-milter 0.97 on milter.postman.i2p
X-Mailer: smtp.postman.i2p - Official I2P Mailer
From: Lunokhod <lunokhod@i2pmail.org>
Content-Type: multipart/signed; boundary="Apple-Mail=_B960EA7B-4971-439E-9BD2-E06C72FBCC61"; protocol="application/pgp-signature"; micalg=pgp-sha512
Subject: 
To: xxx.xxx@xxx.com
Mime-Version: 1.0 (Mac OS X Mail 8.2 \(2070.6\))
Message-Id: <20150318122703.F3F27AE3E9@smtp.postman.i2p>
Date: Wed, 18 Mar 2015 12:27:03 +0000 (UTC)


--Apple-Mail=_B960EA7B-4971-439E-9BD2-E06C72FBCC61
Content-Transfer-Encoding: 7bit
Content-Type: text/plain;
	charset=us-ascii

This is a signed message, send from GPGMail version 2.5b5


--Apple-Mail=_B960EA7B-4971-439E-9BD2-E06C72FBCC61
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
	filename=signature.asc
Content-Type: application/pgp-signature;
	name=signature.asc
Content-Description: Message signed with OpenPGP using GPGMail

-----BEGIN PGP SIGNATURE-----
Comment: GPGTools - https://gpgtools.org

iQEcBAEBCgAGBQJVCPu1AAoJECEwxJzLvm6pW7EIAL7RE8sRhD9J1PDaQA3GuNYh
ukp8nN7sEFAg5kyiaoxF/9cZjJG0b2A2XgHShJQnpU7AlFVvtLErDKLM3W/2IxrQ
70vRd6HD/Sph74ufkAzkLEfTSelE+BJpj+t1WUa4YYkHTaAhMWmAzljXtG01yTlj
DQolfaiGOHhLOYWUShQ1Bj0csUkFNMVNvMqVje/+zekBpnGMrRWDUOAaam1Q24P6
7DCPOWdIdLzT8RLEjOcePhMSp5qDpBn5M6w2xwSATiJsKyu6ORZDTWcsJgXc7wCv
jGKvYKMDDaV1p+h5AfrRbH+HR7vqfXSGFd344mwJoQTKue5DXYkwWHmTJi/MO20=
=ouR/
-----END PGP SIGNATURE-----

--Apple-Mail=_B960EA7B-4971-439E-9BD2-E06C72FBCC61--
```

**Comment by coruus** [comment]
See google/end-to-end#27 for a PR with the start of PGP/MIME support by @diracdeltas. yahoo/end-to-end#2 is a parallel issue for our codebase. I know that @diracdeltas and I would rapidly accept a PR to add this functionality.

**Comment by lunokhod** [comment]
It seems that this functionality is required if end-to-end will ever be used in practice. Is there is reason that there was no action on the original PR?

**Comment by koto** [comment]
End-to-End is a RFC 4880 implementation first, so we prioritize OpenPGP-related fixes and features. The PR in question was already reviewed and comments about the implementations were added, take a look at discussion there.

**Comment by coruus** [comment]
@koto: I think we generally agree with comments; just limited time to address. I'm somewhat perplexed by what you mean by an 'RFC 4880 implementation first'...

@lunokhod: If you want to take a stab at rebasing and addressing the comments @koto mentions...

**Comment by sirdarckcat** [comment]
this might be fixable only on pgpmime clients, @kbsriram cc FYI

closing it for the extension / library, as I dont know if there's anything we can do here
