### ISSUE TITLE
Compose window sometimes way to small (OSX)

### ISSUE THREAD

**Issue by lunokhod** [google/end-to-end#242]
As the attached image shows, when clicking on the end-to-end icon, the compose window is sometimes SUPER SMALL. I have had this problem on several computers, and even though I enventually get it to open properly, I can not find a reproducible way to do this. This has been a recurring problem over the past several months.

![screen shot 2015-03-26 at 18 15 37](https://cloud.githubusercontent.com/assets/8471949/6852362/850539ca-d3e4-11e4-9ea3-a93a61c75cd2.png)

**Comment by dlg-yahoo** [comment]
This is common to pretty much all Chrome extensions; I'm tempted to think it's a Chrome bug, because I've spent some time trying to diagnose it as well. Google folks: Is there a related crbug?

**Comment by koto** [comment]
It looks like https://code.google.com/p/chromium/issues/detail?id=428044

**Comment by sirdarckcat** [comment]
@rcchan @koto what's the status of your ugly workaround? :)

**Comment by koto** [comment]
It's ugly, but works most of the times.

**Comment by sirdarckcat** [comment]
ok cool
