### ISSUE TITLE
ERROR - assignment to property ____ of goog.array

### ISSUE THREAD

**Issue by vinniejames** [google/end-to-end#281]
Getting 9 errors regarding properties assigned to goog.arry when compliing with both grunt default or /.do.sh build_extention:

All dependencies met.
Compiling Soy templates...
Done.
Using previous template build. Run ./do.sh clean if you want to rebuild the templates.
Building End-To-End extension to build/extension
Compiling JS files...
.lib/closure-library/closure/goog/array/array.js:109: ERROR - assignment to property indexOf of goog.array
found   : function (?, ?, ?): ?
required: function ((Array<T>|null|{length: number}), T, number=): number
goog.array.indexOf = goog.NATIVE_ARRAY_PROTOTYPES &&
^

lib/closure-library/closure/goog/array/array.js:151: ERROR - assignment to property lastIndexOf of goog.array
found   : function (?, ?, ?): ?
required: function ((Array<T>|{length: number}), T, (null|number)=): number
goog.array.lastIndexOf = goog.NATIVE_ARRAY_PROTOTYPES &&
^

lib/closure-library/closure/goog/array/array.js:197: ERROR - assignment to property forEach of goog.array
found   : function (?, ?, ?): undefined
required: function ((Array<T>|null|{length: number}), (function (this:S, T, number, ?): ?|null), S=): ?
goog.array.forEach = goog.NATIVE_ARRAY_PROTOTYPES &&
^

lib/closure-library/closure/goog/array/array.js:260: ERROR - assignment to property filter of goog.array
found   : function (?, ?, ?): ?
required: function ((Array<T>|null|{length: number}), (function (this:S, T, number, ?): boolean|null), S=): Array<T>
goog.array.filter = goog.NATIVE_ARRAY_PROTOTYPES &&
^

lib/closure-library/closure/goog/array/array.js:301: ERROR - assignment to property map of goog.array
found   : function (?, ?, ?): ?
required: function ((Array<VALUE>|null|{length: number}), function (this:THIS, VALUE, number, ?): RESULT, THIS=): Array<RESULT>
goog.array.map = goog.NATIVE_ARRAY_PROTOTYPES &&
^

lib/closure-library/closure/goog/array/array.js:346: ERROR - assignment to property reduce of goog.array
found   : function (?, ?, ?, ?): ?
required: function ((Array<T>|null|{length: number}), function (this:S, R, T, number, ?): R, ?, S=): R
goog.array.reduce = goog.NATIVE_ARRAY_PROTOTYPES &&
^

lib/closure-library/closure/goog/array/array.js:391: ERROR - assignment to property reduceRight of goog.array
found   : function (?, ?, ?, ?): ?
required: function ((Array<T>|null|{length: number}), (function (this:S, R, T, number, ?): R|null), ?, S=): R
goog.array.reduceRight = goog.NATIVE_ARRAY_PROTOTYPES &&
^

lib/closure-library/closure/goog/array/array.js:427: ERROR - assignment to property some of goog.array
found   : function (?, ?, ?): ?
required: function ((Array<T>|null|{length: number}), (function (this:S, T, number, ?): boolean|null), S=): boolean
goog.array.some = goog.NATIVE_ARRAY_PROTOTYPES &&
^

lib/closure-library/closure/goog/array/array.js:464: ERROR - assignment to property every of goog.array
found   : function (?, ?, ?): ?
required: function ((Array<T>|null|{length: number}), (function (this:S, T, number, ?): boolean|null), S=): boolean
goog.array.every = goog.NATIVE_ARRAY_PROTOTYPES &&
^

9 error(s), 0 warning(s), 98.3% typed

**Comment by adhintz** [comment]
Sorry for the trouble. This started happening on Friday due to an issue in the latest closure-compiler. I'll change our download-lib.sh as suggested here https://github.com/google/closure-compiler/issues/904
