### ISSUE TITLE
Building results in Property isKeyRingEncrypted never defined on pgpCtx

### ISSUE THREAD

**Issue by mitchell-johnson** [google/end-to-end#283]
When building the extension I am recieving the error:
``` ERROR - Property isKeyRingEncrypted never defined on pgpCtx
        pgpCtx.isKeyRingEncrypted().addCallback(function(isEncrypted)```

in Workfow.js file. A variation of this issue has been posted before https://github.com/google/end-to-end/issues/148 and seems to have been fixed/closed. However, myself and three of my colleagues are currently having the same issue.

**Comment by adhintz** [comment]
Sorry, but I'm not able to reproduce this. If you're able to reproduce this in a fresh git clone, perhaps it's due to something different with your local OS or libraries?

$ git clone git@github.com:google/end-to-end.git
$ cd end-to-end/
$ ./do.sh install_deps && ./do.sh build_extension

**Comment by mitchell-johnson** [comment]
@adhintz Thank you for the prompt reply. Embarrassingly solution in my case was to clone the repo and build it from scratch again. Looking at the old repository, I do not see any reason why my previous clone was playing up but alas there must have been some issue.

**Comment by adhintz** [comment]
Great -- thanks!
