### ISSUE TITLE
getting build error

### ISSUE THREAD

**Issue by voyager106** [google/end-to-end#285]
Just pulled down the most up-to-date version of the code and am getting this after running ./do.sh build_extension:

Building End-To-End extension to build/extension
Compiling JS files...
...lib/closure-library/closure/goog/ui/popupmenu.js:330: ERROR - Parse error. '}' expected
<<<<<<< HEAD
^

1 error(s), 0 warning(s)

**Comment by koto** [comment]
This is https://github.com/google/closure-library/issues/453

**Comment by voyager106** [comment]
thank you, sorry for the duplicate, I'd tried searching several ways but didn't come up with anything like my error.

**Comment by koto** [comment]
Oh don't worry, I actually filed the bug myself based on this issue, that's why you couldn't find anything.

**Comment by voyager106** [comment]
oh, great, thanks for that! I completely missed the sequence of events :)
