### ISSUE TITLE
Compilation error on OS X 10.10.2

### ISSUE THREAD

**Issue by DarkMalloc** [google/end-to-end#286]
Hi guys,

This error is presented upon compilation (from a fresh clone) on a OS X 10.10.2 machine.

```
lib/closure-library/closure/goog/ui/popupmenu.js:330: ERROR - Parse error. '}' expected
```

Is this the appropriate place to raise this, or should I do so in the closure-library repository?

Thanks,

J

**Comment by koto** [comment]
See https://github.com/google/end-to-end/issues/285.
