### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by shuffle2** [google/end-to-end#295]
Almost a year ago I started using e2e. I got it from the googlecode page, made some patches so it would build, and got it working on chrome/windows.  
Recently, chrome has been showing me a nag screen whenever it starts claiming that running a "developer mode" extension may harm my computer. Ironic, but whatever.  
Now, the extension doesn't work anymore:  
`Stack Trace: prompt_binary.js:2513 (anonymous function)`
```
e2e.ext.ui.Prompt.prototype.decorateInternal=function(a){e2e.ext.ui.Prompt.superClass_.decorateInternal.call(this,a);soy.renderElement(a,e2e.ext.ui.templates.prompt.Main,{extName:chrome.i18n.getMessage("extName")});a.querySelector("link").href=chrome.extension.getURL("prompt_styles.css");chrome.runtime.getBackgroundPage(goog.bind(function(a){this.pgpLauncher_=a.launcher||this.pgpLauncher_;console.debug(this.pgpLauncher_);this.pgpLauncher_&&this.pgpLauncher_.getSelectedContent(goog.bind(this.processSelectedContent_,
this))},this))};
```
So I came to grab the latest version, and found that windows support is even less existent now. I find this baffling.

**Comment by koto** [comment]
Adding support for the build environment on Windows is not planned, as none of us is using this platform.  Of course the built extension would work on any Chrome, including Chrome/Win. I'm closing this ticket.

When you say that the extenision "doesn't work anymore", do you mean the current version? If so, please reopen and we'll investigate further.
