### ISSUE TITLE
download-libs.sh fails silently when filesystem doesn't support symlinks.

### ISSUE THREAD

**Issue by daveloyall** [google/end-to-end#301]
See this?  https://github.com/google/end-to-end/blob/master/download-libs.sh#L56

My `~/src` filesystem type is `vboxsf`.  It's a broken fs which silently fails to create symlinks.

...which makes the build fail later.

The solution is to checkout end-to-end into a filesystem with working support for symlinks.

Just thought you should know...

**Comment by koto** [comment]
Interesting. Do you get result code 0 for the ln -s? Supporting broken filesystems is kinda out of scope, but we might be able to workaround by just copying the file if ln -s failed.

**Comment by daveloyall** [comment]
ok, `ln` does provide a non-zero exit code in this case.

    hobbes@metalbaby:~/src$ touch foo; ln -s foo bar; echo $?
    ln: failed to create symbolic link ‘bar’: Read-only file system
    1

I was not aware of that, thank you.
