### ISSUE TITLE
secp256k1 key support

### ISSUE THREAD

**Issue by drewbug** [google/end-to-end#318]
Currently supported by GnuPG 2.1 if you compile the latest libgcrypt yourself, this would mean a lot to me.

**Comment by koto** [comment]
Why do you think it's unsupported? P256 is our default curve for the keys.

**Comment by koto** [comment]
Oh, you mean the Koblitz curve? It's not part of OpenPGP ECC extension (https://tools.ietf.org/html/rfc6637), so you couldn't use it in our main use case. Why would you need that curve? Something Bitcoin related?

**Comment by drewbug** [comment]
@koto, yeah, the Koblitz curve :)

GPG supports it, along with the Brainpool curves and Ed25519, for signing.

My OpenPGP primary key uses secp256k1. Recent versions of the SKS keyserver support this curve, and I'm in the process of adding support for it to Keybase.

**Comment by sirdarckcat** [comment]
@thaidn maybe you and Frank can implement it, since you like these things

**Comment by koto** [comment]
AFAIK almost noone uses secp256k1 curve, apart from Bitcoin crowds. If there are concerns about the seed used in secp256r1, I guess 25519 is much more widely accepted, and a better choice.

**Comment by drewbug** [comment]
Yeah, I'm by no means proposing it be made the default curve or anything, I just want to avoid interoperability issues issues. I'll add it myself when I get a few hours.

**Comment by koto** [comment]
There is a fork of openpgpjs https://github.com/Jaxx-io/openpgpjs-secp256k1/blob/master/README_secp256k1.md that has a (half-baked?) specp256k1 implementation via https://github.com/indutny/elliptic/blob/master/lib/elliptic/curves.js

**Comment by sirdarckcat** [comment]
ok, if there's any interest let me know, otherwise closing this

**Comment by drewbug** [comment]
I'm still interested in this. The newly-released Libgcrypt 1.7 means that GnuPG now includes secp256k1 support by default.
