### ISSUE TITLE
Secure Private Key Synchronization (RFC)

### ISSUE THREAD

**Issue by tanx** [google/end-to-end#320]
Hi,

Tankred from [Whiteout](https://whiteout.io) here. Me, Werner Koch, @koto and other PGP projects discussed a secure way to synchronize a user's private key between devices during the [OpenPGP summit in April](https://www.gnupg.org/blog/20150426-openpgp-summit.html). The goal was to formalize and hopefully standardize a very simple protocol that allows interoperability between mail user agents.

We've already gotten feedback from other vendors using OpenPGP.js such
as 1&1 (GMX/Web.de) that use Mailvelope, and we would also like to hear what the End-to-End
community has to say about it. Here is our current proposal:

https://github.com/whiteout-io/mail-html5/wiki/Secure-OpenPGP-Key-Pair-Synchronization-via-IMAP

Thanks for any feedback!

**Comment by sirdarckcat** [comment]
thanks tankred. closing this as I assume we discussed this on the second summit

**Comment by tanx** [comment]
Yeah. I think you mentioned generating the user's key from a backup code in a deterministic way.
