### ISSUE TITLE
"Main key is invalid." error

### ISSUE THREAD

**Issue by daveloyall** [google/end-to-end#324]
Hello.

First off, I'm new to PKI and I think that I might be trying to do the wrong thing, or maybe just an unnecessary thing.  Please let me know if that is the case.

Goal: Let my e2e know that I've revoked one of my keys. But, don't just delete it? Because then I won't be able to read old emails...?
Extension version: 0.3.1342 (built locally, from commit 3288abc94b3c7b9adc1258a427f779dd584ff50e (2015-07-13))
Screen: Import an OpenPGP Key
Error: Main key is invalid.
Steps to reproduce:
Copy and paste the following, click import.

    -----BEGIN PGP PUBLIC KEY BLOCK-----
    Version: GnuPG v2
    
    mQMuBFVmPjARCADPpKExFRX2VjI32AYmwu+kuScFVQW9mHXykyxDlX8VVbOzeYTs
    V5bcE1YBDkosU+/63j58d22LcDdcaz1Bu9suremilZpNhRSI0FftbHR/60RNPmed
    ME5t05jG/IrzMVtEAAveUBRMJRr/9m0RGLEu1nD4A4bXT2KQX9BArIk2zMnMz0bH
    gmVSzoaDP0S6rQpqyvH7DKaedCe1203Vw318x1qWZORSqDSry4UCTOHpdbJKLkF8
    06aSMB7bY5iksOLOrlDCQPyGmFiZLWQtu1m/9GaYYbKpYw+KuLNWGNI56grg99cn
    nbZBCaq2XaJhF1wyNDqMX6TGiujL5YsFB4Y/AQCfe2bHiZO0i/cTaxlpwSIy9ceq
    fVkbZ42xDvGkEGqaqQf9GTsTFwYbhgUcuVvcSw6dGJqKbGsdcJ7cT3l69k33LkSW
    lJSRwGoxOn4vp1xz2/VWxVjIqhvG0tTH7FfSv30OlyX7LlQ21EVmYtoGYWXsM0Jj
    qDaCxb9JU10uh0VycqpvkG54coPPko+e0u3qU0uXy7qL9xA7lU8drv83FN3hHhx/
    /iyVRmgkZJtSHVYVL9fS03hjusGHEvr8swVFro+qlOaVQ3g2ReB/mISkPC1OHc+8
    DJxYFb2ussNB4u17q4crUTpl8UK/bSaRXB9l7bctqve8ojNx0itwj4Fc2HHszB6q
    LZNrNTH6z7UmZDBxn+lGVC+Vm1q1bbFg6qIyXwCSBwgAm0vJju2mksI0SQgo6U0d
    ARh353IHOtMxEJxspIL/LhAeb6diaVifsF6saJ07sHXl5VLU4dTn/SL7YUroY8ke
    76Ikq+WwPt5138cqQ96kIW3JHm0y5Ur/O5YVFVDBT7ZHMgCAO455CVhB7kZ5GQU3
    0WgrrRUpzKbMG+lbxkqPsQMHRjvgTj0GS0t/IF/+vs9YhS01tRF77GeMnYWTAik2
    G+99PbNAx2524nzwozgiS5wDEOpQ9Go2ijD+HB5ouVzP8vms7+7V2GLacOqf85UR
    UISV1sLSoM9ovSl8aZhGBacvdIkBvJ4KqRUwdgwmVDDHyzbBWg4Z51/j2zfXSzao
    MIh7BCARCAAjBQJVo9Y3HB0CZmlsZXN5c3RlbSBwaHlzaWNhbGx5IGxvc3QACgkQ
    KlC6V5U7UEkaFgD/d+AAis+CbDgeWHXr0zYMg/WUDdzwGtwA6mbjBleoRnwA/04e
    XgCwFLsZR/gufk3oFvb60FCT1J6PebviPbLvHVrOtCREYXZlIExveWFsbCA8ZGF2
    ZUB0aGUtZ29vZC1ndXlzLm5ldD6IgAQTEQgAKAUCVWY+MAIbAwUJAeEzgAYLCQgH
    AwIGFQgCCQoLBBYCAwECHgECF4AACgkQKlC6V5U7UEloggD7BnqsEBx3x6a6XpMj
    KSfrAIsBtZjI3RMLZMh0HWiqIXYA/RAzNKDkfVfRhx/ChqyJFHvWLyB+LdM5glCc
    suRrqeyCuQINBFVmPjAQCADLlvLbonApHKxTaT4m92LJqW87a8kR3zAsRtS5EHRw
    g2/dmX0gNBBq42PV32LEA7bPs0yHOJyWvVxjMZIFGSHEaiJ3xlM3YXzv9HK496Yr
    TDq/qNhF0Tv3zO6YYQ2+PeDs49GFkxM0FvHvI6t1suwAu+Qoqd/UdgD3qGJB+0Sz
    XKHjPEY+78oW2aCcuuquGZWRu7AkwdB6MuMyuE9IafmDzD0xzSfYMnd7VFKGnkda
    DpoItrrRQOSPEWNZvU4Z87XHvfkyBq1gHiIRcIlOze6rr7lzhtQ8lQoukmuk7NsR
    E2JEs2pDfzQ/1RoEw+a3atx/wjPwqtD8ug/cljzNvnfbAAMGB/4kbE5F5SwKUxYZ
    ND6ijXrp1m0j9WgmT7ZKcbV+CGoLixzJcPr/voIejWNfX+dNbzyx/DqBnkIptEW3
    dwAUibfQAg4wUqWeDZgYvvQCip49nx39A4Nuw6fWJcp2fvr7HvLJyUuuWUQ6jOua
    O/ilsLTz4BuM/8Xeqyfx1tjgrz9OHJoCsADI8STPeHGJ0eF0Q4kTcraZeYIMN6+4
    xfH1sT8xjcupmQOC1OspHv4oRafo+mWrY010mu0UsTckpu8VIjbFvwR0fsvHwi3g
    Ue4dJeBJPEDUcvIgDpdx1coahzuEarpVbc6ZCqKtbhHtGOVJ49s+TJzq8ImDoHzj
    cTwuDhvAiGcEGBEIAA8FAlVmPjACGwwFCQHhM4AACgkQKlC6V5U7UElYqwD+Jd60
    7szcIIHfyDD8yYT8uFw6CezKQrl6I6ok6waxC0kA/2QKOGrvzPy6PJWPqw9hWKZs
    KBbHt+DI0eaS5yzbJMRX
    =3e+D
    -----END PGP PUBLIC KEY BLOCK-----

Alternative steps to reproduce: Import this: http://pgp.mit.edu/pks/lookup?op=get&search=0x2A50BA57953B5049

I hope this information helps.

**Comment by koto** [comment]
We don't support (importing and using) revoked key now. This is tracked in #130.
