### ISSUE TITLE
New key is generated without a UID, only with an email address

### ISSUE THREAD

**Issue by NoSubstitute** [google/end-to-end#327]
I created and exported a key with Google's End-to-End encryption module today and it definitely doesn't seem to play well with GPG 2.1.6. I'm thinking it could be because End-to-End seems to create keys <b>without a uid</b>, and only an email address. At least I don't know how to add a uid when creating a new key. I tried creating a key with a uid by typing something like this in the dialogue:
Firstname Lastname <my-email@gmail.com>

But that only created a key with the address <Firstname Lastname <my-email@gmail.com>>.

I've replaced all references to real keys and email addresses with X/Y/A or other similar nonsense.

>gpg --version
gpg (GnuPG) 2.1.6
libgcrypt 1.6.3
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: C:/Users/xxxx/AppData/Roaming/gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

>gpg --import my-email@gmail.com-UNENCRYPTED-keyring-private.asc
gpg: key XXXXXXXX: public key "<my-email@gmail.com>" imported
gpg: key XXXXXXXX/XXXXXXXX: error sending to agent: End of file
gpg: key XXXXXXXX/YYYYYYYY: error sending to agent: Input/output error
gpg: key XXXXXXXX: "<my-email@gmail.com>" not changed
gpg: Total number processed: 4
gpg:               imported: 1
gpg:              unchanged: 1
gpg:       secret keys read: 3

<b>gpg-agent crashes here. Still, the public key is imported.</b>

>gpg -k
pub   nistp256/XXXXXXXX 1970-01-01
uid       [ unknown] <my-email@gmail.com>
sub   nistp256/YYYYYYYY 1970-01-01 nistp256

>gpg -K

<b>No, the secret key isn't listed.
And the public key has a very wrong creation date. It was created today, 2015-07-18.</b>

**Comment by koto** [comment]
In OpenPGP, User ID is just a text field, that usually contains an email address (sometimes with the first,last name as well).  We decided to use e-mail addresses only when generating keys, but support other implementation UIDs, where the e-mail address is only a part of User ID. 

That's unrelated to the ability to import the key into GnuPG - that one is tracked in another issue (but, as I said there, it's most likely something on your end with colliding GnuPGs installations).

**Comment by NoSubstitute** [comment]
Yes, imported keys with UIDs work fine.
I assume, when I finally am able to import the key to GPG properly, that I will be able to add a UID, since I am much more comfortable working with keys with UIDs.

**Comment by NoSubstitute** [comment]
The solution I chose was to instead create an ECC key in GPG 2.1.6 with a UID.
It of course imports and works perfectly in E2E. So, I'll just stay away from key creating in E2E.
Until (if ever) E2E can create UIDs with more than just the email address, I'll stick to that process.
