### ISSUE TITLE
End-to-end still can't import both public and private key when in same file

### ISSUE THREAD

**Issue by NoSubstitute** [google/end-to-end#328]
Reading #205 it looks like it should've been fixed (maybe I'm reading it wrong), but I verified just a few minutes ago that it doesn't work. My public and private keys both import perfectly, if imported in separate files. When in the same file they don't. Actually, nothing happens. It spins a little, but then nothing. No error message. Nothing.

**Comment by koto** [comment]
Would you mind sending a testcase? What is the format of the file you're trying to import?

**Comment by NoSubstitute** [comment]
I'll have to create a bogus keypair first.
I'll do that and get back to you.

They keypair I've tried to import are RSA/4096 keys and, as I said, they import perfectly when done in separate files.

**Comment by NoSubstitute** [comment]
Created example keypair.
https://pastee.org/benm9
Password is 123412341234 which is also the password for the secret key.

gpg -k
pub   rsa4096/3F3F5E59 2015-07-20 [expires: 2015-08-03]
uid       [ultimate] Example Keypair (Pass 123412341234) <example@example.nope>
sub   rsa4096/142D3AD3 2015-07-20 [expires: 2015-08-03]

gpg -K
sec   rsa4096/3F3F5E59 2015-07-20 [expires: 2015-08-03]
uid       [ultimate] Example Keypair (Pass 123412341234) <example@example.nope>
ssb   rsa4096/142D3AD3 2015-07-20 [expires: 2015-08-03]

$ gpg2 --armor --output example-keys.pub.asc --export 3F3F5E59
$ gpg2 --armor --output example-keys.sec.asc --export-secret-keys 3F3F5E59
$ cat example-keys.pub.asc >example-keys.asc
$ cat example-keys.sec.asc >>example-keys.asc

WTH!
Now it of course imports perfectly!

![20150720-e2e4](https://cloud.githubusercontent.com/assets/12572734/8774844/e7d951cc-2ee2-11e5-8852-b87b49ef9575.png)
![20150720-e2e3](https://cloud.githubusercontent.com/assets/12572734/8774842/e7d602f6-2ee2-11e5-9d53-863b918b43f3.png)
![20150720-e2e2](https://cloud.githubusercontent.com/assets/12572734/8774841/e7d601ac-2ee2-11e5-92b0-d38b53b3a7c0.png)
![20150720-e2e1](https://cloud.githubusercontent.com/assets/12572734/8774843/e7d6a5e4-2ee2-11e5-9796-d6fc9c9f68f0.png)

Ok, I'll add more UIDs to the keypair and see if that is the cause. I have three UIDs on the keypair that kept failing for me. Chrome vs Canary wasn't relevant. Empty E2E keyring vs one with content wasn't either.

Now, this is silly. It works!

![20150720-e2e8](https://cloud.githubusercontent.com/assets/12572734/8775101/30360972-2ee5-11e5-9142-47a9d4eb5755.png)
![20150720-e2e7](https://cloud.githubusercontent.com/assets/12572734/8775103/30373f22-2ee5-11e5-8d5c-74de45f920c0.png)
![20150720-e2e6](https://cloud.githubusercontent.com/assets/12572734/8775104/3039073a-2ee5-11e5-83d0-119ad81899df.png)
![20150720-e2e5](https://cloud.githubusercontent.com/assets/12572734/8775102/3036c830-2ee5-11e5-9b09-4f52f09cfc08.png)

I re-exported my own keys exactly the same way. They too imported fine! :-(
Exported the keys with Enigmail in Windows 8.1. They too imported fine! :-(
(Not really disappointed. Sad smileys are for results not being consistent with earlier tries.)

Amazingly, the keyfile from Enigmail is <b>much</b> smaller!
Linux: 20757 byte
Win8.1: 14588 byte

<b>Ok, I can safely say that this works now.</b>

My older exported files are somehow broken. All new exported keys work fine.
Only known factor could be that I've updated to GPG4Win 2.2.5 (which still doesn't support GPG 2.1, but that isn't relevant since I'm only exporting non-ECC keys created with older GPG) on my Windows machine,  and it exports more compatible files. Could also be me who messed up the gpg prefs on earlier endevaours. Enabling compression or whatnot.

Thank you for your patience. Sorry for wasting anyone's time.

**Comment by koto** [comment]
No problem, glad it started working for you. As is mentioned in the other tickets, GnuPG has issues with simultaneous usage of GnuPG 1.4/2.0 and 2.1 that might contribute to the problems you're experiencing. I don't know the root cause, but it's not something we (e2e) could fix.
