### ISSUE TITLE
pgpdump message

### ISSUE THREAD

**Issue by pgpexp** [google/end-to-end#339]

**Comment by koto** [comment]
ECDH. https://tools.ietf.org/html/rfc6637#section-5.

On Sun, Sep 6, 2015 at 1:17 PM, pgpexp <notifications@github.com> wrote:

> pgpdump says this of a standard message with e2e:
>
> New: Public-Key Encrypted Session Key Packet(tag 1)(126 bytes)
>     New version(3)
>     Key ID - 0x......
>     Pub alg - Reserved for Elliptic Curve(pub 18)
>         unknown(pub 18)
>          -> m = sym alg(1 byte) + checksum(2 bytes) + PKCS-1 block type 02
>  New: Symmetrically Encrypted and MDC Packet(tag 18)(219 bytes)
>     Ver 1
>          Encrypted data [sym alg is specified in pub-key encrypted session key]
>         (plain text + MDC SHA1(20 bytes))
>
> Why is unknown? Which algorithm is used for public key encryption?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/end-to-end/issues/339>.
>



-- 
koto@ / Krzysztof Kotowicz / Google
