### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by flamsmark** [google/end-to-end#343]
After checking out `da8a5979f861f6db157c112708ebe976e2a27b39` and running `./do.sh install_deps`, `./do.sh build_extension` is unhappy about something I don't understand:

```
end-to-end git:(master) ./do.sh build_extension                                                                                                                                                                   
All dependencies met.
Using previous template build. Run ./do.sh clean if you want to rebuild the templates.
Building End-To-End extension to build/extension
Compiling JS files...
.lib/closure-templates-compiler/soyutils_usegoog.js:64: ERROR - required "goog.soy.data.UnsanitizedText" namespace never provided
goog.require('goog.soy.data.UnsanitizedText');
^

1 error(s), 0 warning(s)
```

**Comment by adhintz** [comment]
Same here.

**Comment by koto** [comment]
It seems to be caused by this, https://github.com/google/closure-templates/issues/57 , working on a workaround.

**Comment by koto** [comment]
So, the plan was to move the closure templates compiler to a submodule and build it from a pinned commit in `install_deps.sh`, but the project uses Maven instead of Ant and I'd rather not introduce another build dependency to E2E :/ Unfortunately, they don't seem to provide past builds, only the trunk build is available (which is what we are using).  Working on a Maven-based workaround...

**Comment by koto** [comment]
I have a Maven-based workflow, but I cannot find the commit that actually works, fixing this error causes:
```
.lib/closure-templates-compiler/soyutils_usegoog.js:251: ERROR - element TRUSTED_RESOURCE_URI does not exist on this enum
    soydata.SanitizedContentKind.TRUSTED_RESOURCE_URI;
```
This needs to wait til tomorrow, I'm out of time now :/

**Comment by HamishMacEwan** [comment]
Fetched  master e438530eadac1fe862d0eeb144a1f1ac33ce5456 [behind 130] Merge pull request #303 from adhintz/master and had a similar result:

```
./do.sh build_extension
All dependencies met.
All dependencies met.
Compiling Soy templates...
Done.
Using previous template build. Run ./do.sh clean if you want to rebuild the templates.
Building End-To-End extension to build/extension
Compiling JS files...
.lib/closure-templates-compiler/soyutils_usegoog.js:64: ERROR - required "goog.soy.data.UnsanitizedText" namespace never provided
goog.require('goog.soy.data.UnsanitizedText');
^

1 error(s), 0 warning(s)
```
