### ISSUE TITLE
Implement hash truncation for DSA

### ISSUE THREAD

**Issue by koto** [google/end-to-end#345]
Extracted of https://github.com/google/end-to-end/issues/337. Similarly to recent ECDSA fix (https://github.com/google/end-to-end/pull/317) we need to truncate the hash to q length in DSA. Both FIPS 186-4 and https://tools.ietf.org/html/rfc4880#section-5.2.2 require that.

**Comment by hakarune** [comment]
Nice. I'm going to recompile and build tonight, thanks for the quick fix
