### ISSUE TITLE
Private Chat Request

### ISSUE THREAD

**Issue by murdock2** [google/end-to-end#352]
Hello,
   If possible, I would appreciate the opportunity to discuss the Google End-To-End Key Distribution.
Thank you,
Austin Murdock
austinmurdock@cs.berkeley.edu

**Comment by adhintz** [comment]
Please feel free to post any public questions or discussion at https://groups.google.com/forum/#!forum/e2e-discuss

I'll also send you an email in case I can better help route your request.
