### ISSUE TITLE
[Feature Request] Option to pop out by default.

### ISSUE THREAD

**Issue by mjperrone** [google/end-to-end#356]
I had the problem outlined in #275 (I write almost no emails without referring to another tab) and so started exclusively using the windowed pop out. It's pretty annoying to have to do an extra action just to get message durability, so I'd propose there be an option to use the windowed popout by default whenever initializing End-To-End.

**Comment by sirdarckcat** [comment]
the rationale for not starting as a popup was about trusted UI (to prevent phishing attacks).

we can look into it again, but we would need to find a good way to prevent phishing attacks.

**Comment by sirdarckcat** [comment]
please reopen if you would like to argue for this :)
