### ISSUE TITLE
"goog.soy.data.UnsanitizedText" namespace never provided

### ISSUE THREAD

**Issue by HamishMacEwan** [google/end-to-end#358]
```
All dependencies met.
Using previous template build. Run ./do.sh clean if you want to rebuild the templates.
Building End-To-End extension to build/extension
Compiling JS files...
.lib/closure-templates-compiler/soyutils_usegoog.js:64: ERROR - required "goog.soy.data.UnsanitizedText" namespace never provided
goog.require('goog.soy.data.UnsanitizedText');
```
If this is a test to exclude naifs, OK this isn't an issue, otherwise...

**Comment by adhintz** [comment]
I'm not able to reproduce this in a clean clone. Mind please including instructions for how to reproduce this?

This should have been fixed here: https://github.com/google/end-to-end/blob/master/download-libs.sh#L83
as described here: https://github.com/google/end-to-end/issues/343

**Comment by HamishMacEwan** [comment]
In preparing those instructions I find I can no longer reproduce the error.  

Thank you for the response.

**Comment by adhintz** [comment]
Great!
