### ISSUE TITLE
bzip2 error: "invalid packet length new format

### ISSUE THREAD

**Issue by adhintz** [google/end-to-end#364]
as described in pull #363 

From @sykosoft: "I just built and tested, and received: "invalid packet length new format" Thoughts?"

**Comment by adhintz** [comment]
I've been able to reproduce the issue. It looks like some messages work fine (some combination of short and non-repeating symbols) and some messages give the error you describe (longer messages that have repeating symbols).

$ echo "repeatingAAAAAAAAAAAAAAAAAAAAAAZZZZZZZZZZZ" > doc
$ gpg --output doc.gpg --encrypt --recipient rsarsa@pgpkey.example.com --compress-algo bzip2 --armor doc
$ cat doc.gpg 
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMAyMlJx+Vv4ahAQf/ZVAQIY9b+s3dcUqCCH930d3sn3lvR507kxA6PhmfPp7k
ie/pUV/ecTNSsnfdkjCnRb8A2awFSvx9gm9SD/LW2Hq7Gsvg+EYY4uIGHiAkBBlq
Zk4Eqo0UV3Eity9eXcYBx63FcEvoGuSjdIy8Wu/EHUKvT0Kw28QPgSUUGHH6GSCa
cL292z+SGGUaZweHbEX2vcRji44/NrgjR6oiOHPugQORBmZlchyBo0mjGIkvPelB
P3SQ9xAqkYaT/bf9ytDUEZsHEFWf5FM1qzA/kxLjyWTed1L06gMgirJgFhjYbxiN
vhMBnhdDQNjE50oHNHQKRKkdMHCRWGbmM6JRmetuI9J4AbdDZbxFCfPs49Ix55y2
CvrDuE7XRxKzoFmn1IzTI69XJCuzfBUoSCdNBXI9qgfm+ys5qMWw6RTFVyIUPvaH
lc19j1C+SzDvbMHE0q5tCzvUUgDKZYbAUlh7Tn7IGRvEaxXCcis39cEHQetc0Cnw
jqrTaSkGOsNK
=rhih
-----END PGP MESSAGE-----

This is using the test key found in src/javascript/crypto/e2e/openpgp/contextimpl_test.html

**Comment by adhintz** [comment]
@sykosoft if you still see issues with the current code, please let us know. Thanks!

**Comment by sykosoft** [comment]
So far so good except for one blank message which may not be related. I'll let you know if I have further issues, and THANK you.
