### ISSUE TITLE
goog.importScript_(goog.basePath + "deps.js");

### ISSUE THREAD

**Issue by felixhammerl** [google/end-to-end#370]
Steps to reproduce:

* build library
* include via script tag
* see an error popping up from the following line: `goog.importScript_(goog.basePath + "deps.js");`

<img width="974" alt="screen shot 2016-03-28 at 9 28 47 pm" src="https://cloud.githubusercontent.com/assets/1818340/14087826/26c4aae8-f52c-11e5-887a-14ae90e75521.png">

What's this about?

**Comment by sirdarckcat** [comment]
does it work even with the error? or does it abort?

**Comment by felixhammerl** [comment]
it seems to work even with the error, at least i haven't seen it breaking.

**Comment by sirdarckcat** [comment]
ah, then yea, the reason is because closure is looking for the deps file (which says where to find different files when goog.require()). I think this shouldn't happen when goog.COMPILED is true. How did you build the library? as the instructions?

**Comment by felixhammerl** [comment]
yup :)

**Comment by sirdarckcat** [comment]
ok, Im syncing the codebases so will try to fix this on the way

**Comment by sirdarckcat** [comment]
did it fix it?

**Comment by sirdarckcat** [comment]
please reopen if its still a problem
