### ISSUE TITLE
Unable to build on OS X

### ISSUE THREAD

**Issue by sykosoft** [google/end-to-end#393]
Having built many times previously, I attempted to build:

```
All dependencies met.
All dependencies met.
Compiling Soy templates...
Done.
Using previous template build. Run ./do.sh clean if you want to rebuild the templates.
Building End-To-End extension to build/extension
Compiling JS files...
.src/javascript/crypto/e2e/ecc/domainparam.js:201: ERROR - Bad type annotation. type not recognized due to syntax error
 * }>}
   ^

src/javascript/crypto/e2e/ecc/domainparam.js:201: ERROR - Bad type annotation. expected closing }
 * }>}
    ^

src/javascript/crypto/e2e/ecc/point/ed25519.js:358: ERROR - Bad type annotation. type not recognized due to syntax error
 * }} table
   ^

src/javascript/crypto/e2e/ecc/point/nist.js:453: ERROR - Bad type annotation. type not recognized due to syntax error
 * }} table
   ^
```

4 error(s), 0 warning(s)

It seems that the most recent commit failed some checks with the same errors?

**Comment by koto** [comment]
Hey!

Thanks for letting us know - it's probably a dangling comma in object type annotation:

https://github.com/google/end-to-end/blob/master/src/javascript/crypto/e2e/ecc/domainparam.js#L200

**Comment by koto** [comment]
It builds for me on Linux. Could you remove lib directory and `./do.sh install_deps` + '`./do.sh build_extension` again? Perhaps you have some older Closure Compiler in the lib.

**Comment by sykosoft** [comment]
That appears to have solved it. (Only some minor compiler warnings now).
Thank you!

On Mon, Sep 5, 2016 at 7:38 AM, Krzysztof Kotowicz <notifications@github.com
