### ISSUE TITLE
Support for Inbox by Google

### ISSUE THREAD

**Issue by zimme** [google/end-to-end#394]
Hey

So this is a question and depending on the answer, a feature request too.

Is this usable with "Inbox by Google"? if not, could it support it or are the
two products too different?

**Comment by peterrosell** [comment]
+1

**Comment by dkudriavtsev** [comment]
+1

**Comment by sirdarckcat** [comment]
Hi

Sorry for the delay - we haven't discussed this with the Inbox team, but we'll come back to this once we have a chance to look at the chrome extension part of the project.

**Comment by u269c** [comment]
It's working for me with Inbox.
I am using a fresh build of the extension from January.

@zimme : what issues are you having with it?

**Comment by zimme** [comment]
@u269c, awesome.

When I filed this issue it was more of a question because I hadn't tried the extension yet.
