### ISSUE TITLE
Add support for PGP / MIME

### ISSUE THREAD

**Issue by koto** [google/end-to-end#69]
_From [tankred@whiteout.io](https://code.google.com/u/tankred@whiteout.io/) on June 06, 2014 11:36:13_

  
If you're interested in supporting PGP/MIME for attachments, we have written MIME-codec for our application:   
  
MIME encoding: <https://github.com/whiteout-io/mailbuild>  
MIME decoding: <https://github.com/whiteout-io/mimeparser>  
  
The code is MIT licensed and is part of our email.js effort:  
<http://emailjs.org>  
  
Looking forward to your feedback. Thanks  
Tankred  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=32>

**Comment by sirdarckcat** [comment]
In case you are following this - https://github.com/google/end-to-end/pull/323

**Comment by sirdarckcat** [comment]
https://github.com/google/end-to-end/pull/323 fixed this
