### ISSUE TITLE
Figure out a way to deal with key metadata UX-wise

### ISSUE THREAD

**Issue by koto** [google/end-to-end#77]
_From [evn@google.com](https://code.google.com/u/evn@google.com/) on June 07, 2014 02:39:48_

  
The extension doesn't honor expired keys yet.  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=40>

**Comment by sirdarckcat** [comment]
@kbsriram this was fixed right?

**Comment by sirdarckcat** [comment]
cleaning up old bugs, please reopen if you would still like to see this fixed
