### ISSUE TITLE
Figure out a way to deal with slow operations UX wise

### ISSUE THREAD

**Issue by koto** [google/end-to-end#78]
_From [evn@google.com](https://code.google.com/u/evn@google.com/) on June 07, 2014 02:41:03_

  
Reproduction steps:   
1\. Import public keys for multiple recipients (4+).   
2\. Compose a message and include multiple recipients on the To line.   
3\. Press 'Protect this message'   
  
What do you see?   
There isn't any feedback that the user pressed the Protect button. It left me wondering if I had pressed the button, or if the extension had become unresponsive.   
  
What do you expect instead?   
Change the color of the button or display a progress bar when encrypting the message.  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=41>

**Comment by koto** [comment]
This can be solved by using the WorkerContextImpl instead of ContextImpl in the launcher, but some UI interactions should be blocked then during crypto operations.

**Comment by sirdarckcat** [comment]
we can do this for ECC keys via webcrypto rather than workers now, so this should be easy now

**Comment by sirdarckcat** [comment]
cleaning up old bugs, please reopen if you would still like to see this fixed
