### ISSUE TITLE
UX for "bad chips" isn't very user-friendly

### ISSUE THREAD

**Issue by koto** [google/end-to-end#79]
_From [evn@google.com](https://code.google.com/u/evn@google.com/) on June 07, 2014 02:45:33_

  
Reproduction steps:   
1\. Compose message   
2\. Type in email address of someone who's key you don't have   
3\. See their name in red, but have no idea why.   
  
What do you see?   
  
User's name in red.   
  
What do you expect instead?   
  
A prompt to import their key or invite them to use End-to-End?   
  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=42>

**Comment by koto** [comment]
Now this also concerns users with a key successfully fetched from the keyserver. Chips stay red.

**Comment by diracdeltas** [comment]
I did some UI work in the Yahoo fork for this. Will open as a pull req if you don't fix it earlier. 

     On Wednesday, January 14, 2015 4:28 PM, Krzysztof Kotowicz <notifications@github.com> wrote:
   

 Now this also concerns users with a key successfully fetched from the keyserver. Chips stay red.—

**Comment by sirdarckcat** [comment]
hey @diracdeltas did you send the PR for that?

**Comment by diracdeltas** [comment]
> hey @diracdeltas did you send the PR for that?

Nope

**Comment by sirdarckcat** [comment]
cleaning up old bugs, please reopen if you would still like to see this fixed
