### ISSUE TITLE
Multiple Devices

### ISSUE THREAD

**Issue by koto** [google/end-to-end#88]
_From [evn@google.com](https://code.google.com/u/evn@google.com/) on June 07, 2014 03:06:15_

  
Explain what users should do with multiple devices (similar to Key Backup in [ issue 46 ](/p/end-to-end/issues/detail?id=46))  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=51>

**Comment by sirdarckcat** [comment]
@rcchan you are working on this (per the other thread re: key backup)

**Comment by sirdarckcat** [comment]
(that was a question, sorry :)

**Comment by rcchan** [comment]
It looks like I started work on this some time last year.  I'm not sure the linked bug at the top of this thread is correct though, so can you clarify again the context of this issue?

**Comment by sirdarckcat** [comment]
oh, I meant - the fix for the key backup would fix this too

**Comment by rcchan** [comment]
Key backup and restore should allow a user to use the same keys on multiple devices. I'm not sure if that answers the question, but there was a recent merge for the backup/restore keys.

**Comment by sirdarckcat** [comment]
yeah, that's what I meant.

this bug was about adding support for multiple devices. we had disabled it by accident so if it's enabled now, we can close it now
